# Generated by Django 3.1.7 on 2022-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Trial', 'Trial'), ('Enterprise', 'Enterprise'), ('Workspaces', 'Workspaces')], max_length=15)),
                ('maxTier', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('BD', 'Bd'), ('GENERAL', 'General')], max_length=15)),
                ('currency', models.CharField(choices=[('BDT', 'Bdt'), ('USD', 'Usd')], max_length=5)),
                ('pricing', models.IntegerField()),
                ('validity', models.IntegerField(default=30)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
