# Generated by Django 3.1.7 on 2022-01-19 08:06

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('uniqueName', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Trading Company', 'Trading Company'), ('Buying Office', 'Buying Office'), ('Agent', 'Agent'), ('Distributor/Wholesaler', 'Distri'), ('Government ministry/Bureau/Commission', 'Gover'), ('Association', 'Assoc'), ('Business Service (Transportation, finance, travel, Ads, etc)', 'Business'), ('other', 'Other')], default='other', max_length=60)),
                ('optionalRole', models.CharField(choices=[('editProfile', 'Editprofile'), ('cRUDAnnouncement', 'Crud'), ('archiveProject', 'Archive'), ('addRemoveModerator', 'Addremove'), ('messageAssociate', 'Message'), ('addAcceptRejectAssociate', 'Addaccept'), ('acceptRejectProjectFromAssociate', 'Acceptrej')], max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('about', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=255)),
                ('legalOwnerName', models.CharField(max_length=30)),
                ('legalOwnerMail', models.EmailField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('websites', models.CharField(blank=True, max_length=50)),
                ('regisTrationYear', models.DateField()),
                ('totalEmployees', models.CharField(choices=[('Fewer than 5 People', 'Fewer'), ('5 - 10 People', 'Five'), ('11 - 50 People', 'Eleven'), ('51 - 100 People', 'Fifty'), ('101 - 200 People', 'Hundred'), ('201 - 300 People', 'Two Hundred'), ('301 - 500 People', 'Three Hundred'), ('501 - 1000 People', 'Five Hundred'), ('Above 1000 People', 'Above')], max_length=30)),
                ('officeSize', models.CharField(choices=[('below 100 square meters', 'Below'), ('101 - 500 square meters', 'Hundred'), ('501 - 1000 square meters', 'Five Hundred'), ('1001 -2000 square meters', 'One Thousand'), ('above 2000 square meters', 'Above')], max_length=30)),
                ('parentcom', models.CharField(max_length=30)),
                ('removed', models.BooleanField(default=0)),
                ('create_at', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superAdmin', 'Superadmin'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=15)),
                ('designations', models.CharField(blank=True, max_length=20)),
                ('removed', models.BooleanField(default=0)),
                ('isApproved', models.BooleanField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_member', to=settings.AUTH_USER_MODEL)),
                ('approvedBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireAt', models.DateField(default=company.models.one_year_from_today)),
                ('isActive', models.BooleanField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriiption', models.CharField(blank=True, max_length=2500)),
                ('outline', models.CharField(blank=True, max_length=5000)),
                ('deadline', models.DateField(blank=True, default=company.models.one_month_from_today)),
                ('color', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(default='not-started', max_length=30)),
                ('OptionalRole', models.CharField(choices=[('updateArchiveProject', 'Updatearchiveproject'), ('updateProjectPreface', 'Updateprojectpreface'), ('addFileProject', 'Addfileproject'), ('addRemoveMemberRoom', 'Addremovememberroom'), ('createUpdateRoom', 'Createupdateroom'), ('archiveRoom', 'Archiveroom'), ('createUpdateBoard', 'Createupdateboard'), ('createUpdateColumn', 'Createupdatecolumn'), ('assignDeleteMemberBoard', 'Assigndeletememberboard')], default=None, max_length=30)),
                ('files', models.FileField(blank=True, upload_to='')),
                ('timeSpent', models.IntegerField(default=0)),
                ('budget', models.IntegerField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=15)),
                ('version', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('concernedAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.member')),
            ],
        ),
    ]
